version: "3"
services:
  backend:
    build:  
      context: ./
      dockerfile: docker/backend/prod/Dockerfile
    networks:
      - justsomenetwork
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8090:8090"
    healthcheck:
      test: wget backend:8090
      interval: 1s
      timeout: 3s
      retries: 30
  frontend:
    build: 
      context: ./
      dockerfile: docker/frontend/prod/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - justsomenetwork
volumes:
  pgdata:
networks:
  justsomenetwork:
